# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a591dec9b0769deb3c43dcee2c9a9488f9d5dc4869a6d5f28f0a15331ccb652856b21218d61c144d3e2d5147211fd583dbde3af08bc58a938e41c2d6b5c7d47

test:
  secret_key_base: 145d9e663eb151d06217562858b80c66ee35090d8ae9e0d9a7b88b5160bb01794991cd47b7e3ae1759be869a15ce1d4ec87677d460de266de08490f07ffd49f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
